[package]
name = "vimscript-parser"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
pest = { version = "2.7.10", default-features = false }
pest_derive = { version = "2.7.10", default-features = false }

[features]
std = ["pest/std", "pest_derive/std"]

